// Export — turn a completed analysis into shareable Markdown, or a self-contained
// HTML report (inline CSS, opens offline). Covers the core scan; on-demand lens
// results live in their tabs and aren't included here.

export function toMarkdown(d) {
  if (!d) return '';
  const out = [];
  const push = (...l) => out.push(...l);

  push(`# ${d.repoId || 'Repository'}`, '');
  if (d.description) push(`> ${d.description}`, '');
  const meta = [d.language, d.license, d.stars ? `${d.stars}★` : null, d.platform].filter(x => x && x !== 'Unknown');
  if (meta.length) push(meta.join(' · '), '');
  if (d.health && d.health.score != null) push(`**Health:** ${d.health.score}/100${d.health.summary ? ` — ${d.health.summary}` : ''}`, '');

  const para = (title, body) => { if (body) push(`## ${title}`, '', body, ''); };
  const kvList = (title, obj) => {
    if (obj && Object.values(obj).some(Boolean)) {
      push(`## ${title}`, '');
      for (const [k, v] of Object.entries(obj)) if (v) push(`- **${k.replace(/_/g, ' ')}:** ${v}`);
      push('');
    }
  };

  para('ELI5', d.eli5);
  para('Technical', d.technical);
  kvList('Use Cases', d.use_cases);
  kvList('Skip If', d.skip_if);
  para('Enables', d.enables);

  if (d.pros?.length || d.cons?.length) {
    push('## Pros & Cons', '');
    if (d.pros?.length) { push('**Pros**'); d.pros.forEach(p => push(`- ${p}`)); push(''); }
    if (d.cons?.length) { push('**Cons**'); d.cons.forEach(c => push(`- ${c}`)); push(''); }
  }
  if (d.alternatives?.length) { push('## Alternatives', ''); d.alternatives.forEach(a => push(`- **${a.name}** — ${a.when}`)); push(''); }
  if (d.tech_stack?.built_with?.length || d.tech_stack?.key_dependencies?.length) {
    push('## Tech Stack', '');
    if (d.tech_stack.built_with?.length) push(`Built with: ${d.tech_stack.built_with.join(', ')}`, '');
    if (d.tech_stack.key_dependencies?.length) { push('**Key dependencies**'); d.tech_stack.key_dependencies.forEach(k => push(`- \`${k.name}\` — ${k.purpose}`)); push(''); }
  }
  if (d.red_flags?.length) { push('## Red Flags', ''); d.red_flags.forEach(f => push(`- ${f.severity === 'ok' ? '✅' : '⚠️'} **${f.title}** — ${f.text}`)); push(''); }
  if (d.start_here?.length) { push('## Start Here', ''); d.start_here.forEach(e => push(`- ${e.icon || ''} **${e.title}** (${e.tag}) — ${e.desc}`)); push(''); }

  push('---', '_Generated by RepoLens._');
  return out.join('\n');
}

const escapeHtml = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// Minimal Markdown → HTML for our structured export (headings, lists, quote,
// hr, **bold**, `code`). Not a general-purpose converter.
function mdToHtml(md) {
  const inline = (s) => escapeHtml(s).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/`(.+?)`/g, '<code>$1</code>');
  const out = [];
  let inList = false;
  const closeList = () => { if (inList) { out.push('</ul>'); inList = false; } };
  for (const raw of md.split('\n')) {
    const line = raw.trimEnd();
    if (/^### /.test(line)) { closeList(); out.push(`<h3>${inline(line.slice(4))}</h3>`); }
    else if (/^## /.test(line)) { closeList(); out.push(`<h2>${inline(line.slice(3))}</h2>`); }
    else if (/^# /.test(line)) { closeList(); out.push(`<h1>${inline(line.slice(2))}</h1>`); }
    else if (/^> /.test(line)) { closeList(); out.push(`<blockquote>${inline(line.slice(2))}</blockquote>`); }
    else if (/^- /.test(line)) { if (!inList) { out.push('<ul>'); inList = true; } out.push(`<li>${inline(line.slice(2))}</li>`); }
    else if (line === '---') { closeList(); out.push('<hr>'); }
    else if (line === '') { closeList(); }
    else { closeList(); out.push(`<p>${inline(line)}</p>`); }
  }
  closeList();
  return out.join('\n');
}

const REPORT_CSS = `
  body { max-width: 760px; margin: 40px auto; padding: 0 24px; background: #faf9f5; color: #1d1d1f;
    font: 16px/1.65 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
  h1 { font-size: 32px; letter-spacing: -0.5px; margin: 0 0 4px; }
  h2 { font-size: 20px; margin: 32px 0 8px; padding-bottom: 6px; border-bottom: 1px solid #e6dfd8; }
  h3 { font-size: 16px; margin: 20px 0 6px; }
  blockquote { margin: 0 0 16px; color: #6c6a64; font-size: 15px; }
  ul { padding-left: 22px; } li { margin: 4px 0; }
  code { background: #efe9de; border-radius: 4px; padding: 1px 5px; font: 13px ui-monospace, monospace; }
  hr { border: none; border-top: 1px solid #e6dfd8; margin: 32px 0 12px; }
  p:last-of-type { color: #8e8b82; font-size: 13px; }
`;

export function toHtml(d) {
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>RepoLens — ${escapeHtml(d?.repoId || 'Report')}</title>
<style>${REPORT_CSS}</style></head>
<body><main>${mdToHtml(toMarkdown(d))}</main></body></html>`;
}

export function slugify(s) {
  return String(s || 'repo').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'repo';
}
