// Export — turn a completed analysis into shareable Markdown, or a self-contained
// HTML report (inline CSS, opens offline). Covers the core scan; on-demand lens
// results live in their tabs and aren't included here.

import { escapeHtml } from './safe-html.js';

export function toMarkdown(d) {
  if (!d) return '';
  const out = [];
  const push = (...l) => out.push(...l);

  push(`# ${d.repoId || 'Repository'}`, '');
  if (d.description) push(`> ${d.description}`, '');
  const meta = [d.language, d.license, d.stars ? `${d.stars}★` : null, d.platform].filter(x => x && x !== 'Unknown');
  if (meta.length) push(meta.join(' · '), '');
  if (d.health && d.health.score != null) push(`**Health:** ${d.health.score}/100${d.health.summary ? ` — ${d.health.summary}` : ''}`, '');

  const para = (title, body) => { if (body) push(`## ${title}`, '', body, ''); };
  const kvList = (title, obj) => {
    if (obj && Object.values(obj).some(Boolean)) {
      push(`## ${title}`, '');
      for (const [k, v] of Object.entries(obj)) if (v) push(`- **${k.replace(/_/g, ' ')}:** ${v}`);
      push('');
    }
  };

  para('ELI5', d.eli5);
  para('Technical', d.technical);
  kvList('Use Cases', d.use_cases);
  kvList('Skip If', d.skip_if);
  para('Enables', d.enables);

  if (d.pros?.length || d.cons?.length) {
    push('## Pros & Cons', '');
    if (d.pros?.length) { push('**Pros**'); d.pros.forEach(p => push(`- ${p}`)); push(''); }
    if (d.cons?.length) { push('**Cons**'); d.cons.forEach(c => push(`- ${c}`)); push(''); }
  }
  if (d.alternatives?.length) { push('## Alternatives', ''); d.alternatives.forEach(a => push(`- **${a.name}** — ${a.when}`)); push(''); }
  if (d.tech_stack?.built_with?.length || d.tech_stack?.key_dependencies?.length) {
    push('## Tech Stack', '');
    if (d.tech_stack.built_with?.length) push(`Built with: ${d.tech_stack.built_with.join(', ')}`, '');
    if (d.tech_stack.key_dependencies?.length) { push('**Key dependencies**'); d.tech_stack.key_dependencies.forEach(k => push(`- \`${k.name}\` — ${k.purpose}`)); push(''); }
  }
  if (d.red_flags?.length) { push('## Red Flags', ''); d.red_flags.forEach(f => push(`- ${f.severity === 'ok' ? '✅' : '⚠️'} **${f.title}** — ${f.text}`)); push(''); }
  if (d.start_here?.length) { push('## Start Here', ''); d.start_here.forEach(e => push(`- ${e.icon || ''} **${e.title}** (${e.tag}) — ${e.desc}`)); push(''); }

  push('---', '_Generated by RepoLens._');
  return out.join('\n');
}

// Minimal Markdown → HTML for our structured export (headings, lists, quote,
// hr, **bold**, `code`). Not a general-purpose converter.
function mdToHtml(md) {
  const inline = (s) => escapeHtml(s).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/`(.+?)`/g, '<code>$1</code>');
  const out = [];
  let inList = false;
  const closeList = () => { if (inList) { out.push('</ul>'); inList = false; } };
  for (const raw of md.split('\n')) {
    const line = raw.trimEnd();
    if (/^### /.test(line)) { closeList(); out.push(`<h3>${inline(line.slice(4))}</h3>`); }
    else if (/^## /.test(line)) { closeList(); out.push(`<h2>${inline(line.slice(3))}</h2>`); }
    else if (/^# /.test(line)) { closeList(); out.push(`<h1>${inline(line.slice(2))}</h1>`); }
    else if (/^> /.test(line)) { closeList(); out.push(`<blockquote>${inline(line.slice(2))}</blockquote>`); }
    else if (/^- /.test(line)) { if (!inList) { out.push('<ul>'); inList = true; } out.push(`<li>${inline(line.slice(2))}</li>`); }
    else if (line === '---') { closeList(); out.push('<hr>'); }
    else if (line === '') { closeList(); }
    else { closeList(); out.push(`<p>${inline(line)}</p>`); }
  }
  closeList();
  return out.join('\n');
}

const REPORT_CSS = `
  body { max-width: 760px; margin: 40px auto; padding: 0 24px; background: #faf9f5; color: #1d1d1f;
    font: 16px/1.65 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
  h1 { font-size: 32px; letter-spacing: -0.5px; margin: 0 0 4px; }
  h2 { font-size: 20px; margin: 32px 0 8px; padding-bottom: 6px; border-bottom: 1px solid #e6dfd8; }
  h3 { font-size: 16px; margin: 20px 0 6px; }
  blockquote { margin: 0 0 16px; color: #6c6a64; font-size: 15px; }
  ul { padding-left: 22px; } li { margin: 4px 0; }
  code { background: #efe9de; border-radius: 4px; padding: 1px 5px; font: 13px ui-monospace, monospace; }
  hr { border: none; border-top: 1px solid #e6dfd8; margin: 32px 0 12px; }
  p:last-of-type { color: #8e8b82; font-size: 13px; }
`;

export function toHtml(d) {
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>RepoLens — ${escapeHtml(d?.repoId || 'Report')}</title>
<style>${REPORT_CSS}</style></head>
<body><main>${mdToHtml(toMarkdown(d))}</main></body></html>`;
}

export function slugify(s) {
  return String(s || 'repo').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'repo';
}

/**
 * A compact Slack/Discord-friendly message summarising the repo verdict.
 * Plain text with emoji, ≤280 chars for the header + body, no Markdown links.
 */
export function toSlackPost(d, fitLevel) {
  if (!d?.repoId) return '';
  const fitMark = { strong: '✅', solid: '✓', care: '⚠️', risky: '🔴' }[fitLevel] || '•';
  const stars = d.stars ? ` · ${d.stars >= 1000 ? (d.stars / 1000).toFixed(1) + 'k' : d.stars}★` : '';
  const lang = d.language ? ` · ${d.language}` : '';
  const score = d.health?.score ? ` · health ${d.health.score}/100` : '';
  const header = `${fitMark} *${d.repoId}*${stars}${lang}${score}`;
  const desc = (d.bottom_line || d.description || '').slice(0, 140);
  const topPro = (d.pros || [])[0] ? `✔ ${(d.pros || [])[0]}` : '';
  const topCon = (d.cons || [])[0] ? `✖ ${(d.cons || [])[0]}` : '';
  const extras = [topPro, topCon].filter(Boolean).join('  ');
  return [header, desc, extras].filter(Boolean).join('\n');
}

/**
 * A concise integration scaffold — drop this into your repo as CLAUDE.md, a
 * Notion page, or an Obsidian note. Includes fit verdict, decision, capabilities,
 * caveats, and a ready-to-edit integration checklist.
 * @param {object} d - analysis payload
 * @param {{ decision?: string, note?: string } | null} [decision] - saved adoption decision
 * @returns {string}
 */
export function toScaffold(d, decision) {
  if (!d) return '';
  const out = [];
  const push = (...l) => out.push(...l);

  const repoName = (d.repoId || '').split('/').pop() || d.repoId || 'repo';
  push(`# ${d.repoId || 'Repository'}`, '');
  if (d.description) push(`> ${d.description}`, '');

  // Fit verdict + decision
  const score = d.health?.score ?? 0;
  const fitLabel = score >= 85 ? 'Strong Fit' : score >= 70 ? 'Solid Fit' : score > 0 ? 'Needs Care' : 'Unrated';
  push(`**Fit:** ${fitLabel}`);
  if (decision?.decision) {
    const LABELS = { adopt: 'Adopt', trial: 'Trial', hold: 'Hold', reject: 'Reject' };
    push(`**Decision:** ${LABELS[decision.decision] || decision.decision}`);
    if (decision.note) push(`**Note:** ${decision.note}`);
  }
  push('');

  // Capabilities
  const caps = Array.isArray(d.capabilities) ? d.capabilities : [];
  if (caps.length) {
    push('## Capabilities', '');
    caps.forEach(c => push(`- ${c}`));
    push('');
  }

  // Integration checklist
  push('## Integration Checklist', '');
  push('- [ ] Read the README and quickstart guide');
  if (d.start_here?.length) {
    d.start_here.forEach(e => push(`- [ ] ${e.title}${e.desc ? ` — ${e.desc}` : ''}`));
  } else {
    push(`- [ ] Install \`${repoName}\``);
    push('- [ ] Run the examples / tests locally');
    push('- [ ] Review the changelog for breaking changes');
  }
  push('- [ ] Add to project dependencies', '');

  // Key caveats from red flags
  const warns = (d.red_flags || []).filter(f => f && f.severity !== 'ok');
  if (warns.length) {
    push('## Caveats', '');
    warns.forEach(f => push(`- ⚠️ **${f.title}** — ${f.text}`));
    push('');
  }

  // Alternatives considered
  if (d.alternatives?.length) {
    push('## Alternatives Considered', '');
    d.alternatives.forEach(a => push(`- **${a.name}** — ${a.when}`));
    push('');
  }

  push('---', `_Scaffold generated by RepoLens · ${new Date().toISOString().slice(0, 10)}_`);
  return out.join('\n');
}
