import { describe, it, expect } from 'vitest';
import { toMarkdown, toHtml, toScaffold, slugify } from '../exporter.js';

const data = {
  repoId: 'facebook/react', description: 'The library for web UIs.', language: 'JavaScript', license: 'MIT', stars: 228000, platform: 'github',
  health: { score: 94, summary: 'Healthy.' },
  eli5: 'Build UIs from components.', technical: 'Virtual DOM + fiber.',
  use_cases: { core_fit: 'SPAs', good_fit: '', works_well: '', long_term: '' },
  skip_if: {}, enables: 'A big ecosystem.',
  pros: ['Ecosystem'], cons: ['Boilerplate'],
  alternatives: [{ name: 'Vue', when: 'Gentler curve' }],
  tech_stack: { built_with: ['JavaScript', 'TypeScript'], key_dependencies: [{ name: 'scheduler', purpose: 'scheduling' }] },
  red_flags: [{ severity: 'ok', title: 'Healthy', text: 'Frequent releases.' }],
  start_here: [{ icon: '📦', title: 'packages/react', desc: 'Core', tag: 'START' }],
};

describe('toMarkdown', () => {
  it('renders the core analysis sections', () => {
    const md = toMarkdown(data);
    expect(md).toContain('# facebook/react');
    expect(md).toContain('> The library for web UIs.');
    expect(md).toContain('**Health:** 94/100 — Healthy.');
    expect(md).toContain('## ELI5');
    expect(md).toContain('Build UIs from components.');
    expect(md).toContain('- **core fit:** SPAs');
    expect(md).toContain('**Pros**');
    expect(md).toContain('- **Vue** — Gentler curve');
    expect(md).toContain('Built with: JavaScript, TypeScript');
    expect(md).toContain('`scheduler` — scheduling');
    expect(md).toContain('_Generated by RepoLens._');
  });
  it('omits empty sections and returns empty for null', () => {
    expect(toMarkdown(null)).toBe('');
    expect(toMarkdown({ repoId: 'x/y' })).not.toContain('## ELI5');
  });
});

describe('toHtml', () => {
  it('produces a self-contained HTML doc with inline CSS and escaped content', () => {
    const html = toHtml({ ...data, description: 'A & B <tag>' });
    expect(html.startsWith('<!DOCTYPE html>')).toBe(true);
    expect(html).toContain('<style>');
    expect(html).toContain('<h1>facebook/react</h1>');
    expect(html).toContain('A &amp; B &lt;tag&gt;'); // escaped, no raw HTML injection
    expect(html).toContain('<strong>Health:</strong>');
  });
});

describe('toScaffold', () => {
  const scaffoldData = {
    repoId: 'facebook/react', description: 'The library for web UIs.',
    health: { score: 94 }, capabilities: ['frontend', 'ui', 'ssr'],
    start_here: [{ title: 'Install', desc: 'npm install react', tag: 'START' }],
    red_flags: [{ severity: 'warn', title: 'Size', text: 'Bundle can grow large.' }],
    alternatives: [{ name: 'Vue', when: 'Gentler curve' }],
  };

  it('includes repo name, fit, and checklist', () => {
    const md = toScaffold(scaffoldData);
    expect(md).toContain('# facebook/react');
    expect(md).toContain('**Fit:**');
    expect(md).toContain('## Integration Checklist');
    expect(md).toContain('- [ ] Install');
    expect(md).toContain('_Scaffold generated by RepoLens');
  });

  it('includes capabilities', () => {
    const md = toScaffold(scaffoldData);
    expect(md).toContain('## Capabilities');
    expect(md).toContain('- frontend');
  });

  it('includes caveats from warn-severity red flags', () => {
    const md = toScaffold(scaffoldData);
    expect(md).toContain('## Caveats');
    expect(md).toContain('Bundle can grow large');
  });

  it('includes decision when provided', () => {
    const md = toScaffold(scaffoldData, { decision: 'adopt', note: 'Great for us' });
    expect(md).toContain('**Decision:** Adopt');
    expect(md).toContain('**Note:** Great for us');
  });

  it('omits decision block when not provided', () => {
    const md = toScaffold(scaffoldData);
    expect(md).not.toContain('**Decision:**');
  });

  it('returns empty string for null', () => {
    expect(toScaffold(null)).toBe('');
  });
});

describe('slugify', () => {
  it('makes a filesystem-safe slug', () => {
    expect(slugify('facebook/react')).toBe('facebook-react');
    expect(slugify('')).toBe('repo');
  });
});
